// Code generated by MockGen. DO NOT EDIT.
// Source: tempfile.go
//
// Generated by this command:
//
//	mockgen -destination=../internal/tests/mocks/basicRPC/rpc.go -package=basicRPC -mock_names=BasicProviderInterface=BasicRPC -source=tempfile.go BasicProviderInterface
//

// Package basicRPC is a generated GoMock package.
package basicRPC

import (
	context "context"
	reflect "reflect"

	felt "github.com/NethermindEth/juno/core/felt"
	rpcv10 "github.com/NethermindEth/starknet.go/rpc/rpcv10"
	rpcv9 "github.com/NethermindEth/starknet.go/rpc/rpcv9"
	types "github.com/NethermindEth/starknet.go/rpc/types"
	gomock "go.uber.org/mock/gomock"
)

// MockRPCProviderV10Copy is a mock of RPCProviderV10Copy interface.
type MockRPCProviderV10Copy struct {
	ctrl     *gomock.Controller
	recorder *MockRPCProviderV10CopyMockRecorder
	isgomock struct{}
}

// MockRPCProviderV10CopyMockRecorder is the mock recorder for MockRPCProviderV10Copy.
type MockRPCProviderV10CopyMockRecorder struct {
	mock *MockRPCProviderV10Copy
}

// NewMockRPCProviderV10Copy creates a new mock instance.
func NewMockRPCProviderV10Copy(ctrl *gomock.Controller) *MockRPCProviderV10Copy {
	mock := &MockRPCProviderV10Copy{ctrl: ctrl}
	mock.recorder = &MockRPCProviderV10CopyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCProviderV10Copy) EXPECT() *MockRPCProviderV10CopyMockRecorder {
	return m.recorder
}

// BlockHashAndNumber mocks base method.
func (m *MockRPCProviderV10Copy) BlockHashAndNumber(ctx context.Context) (uint64, *felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockHashAndNumber", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(*felt.Felt)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BlockHashAndNumber indicates an expected call of BlockHashAndNumber.
func (mr *MockRPCProviderV10CopyMockRecorder) BlockHashAndNumber(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockHashAndNumber", reflect.TypeOf((*MockRPCProviderV10Copy)(nil).BlockHashAndNumber), ctx)
}

// Call mocks base method.
func (m *MockRPCProviderV10Copy) Call(ctx context.Context, call types.FunctionCall, block types.BlockID) ([]*felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", ctx, call, block)
	ret0, _ := ret[0].([]*felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Call indicates an expected call of Call.
func (mr *MockRPCProviderV10CopyMockRecorder) Call(ctx, call, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockRPCProviderV10Copy)(nil).Call), ctx, call, block)
}

// ChainID mocks base method.
func (m *MockRPCProviderV10Copy) ChainID(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainID", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChainID indicates an expected call of ChainID.
func (mr *MockRPCProviderV10CopyMockRecorder) ChainID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainID", reflect.TypeOf((*MockRPCProviderV10Copy)(nil).ChainID), ctx)
}

// EstimateFee mocks base method.
func (m *MockRPCProviderV10Copy) EstimateFee(ctx context.Context, requests []types.BroadcastTxn, simulationFlags []types.SimulationFlag, blockID types.BlockID) ([]types.FeeEstimation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateFee", ctx, requests, simulationFlags, blockID)
	ret0, _ := ret[0].([]types.FeeEstimation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateFee indicates an expected call of EstimateFee.
func (mr *MockRPCProviderV10CopyMockRecorder) EstimateFee(ctx, requests, simulationFlags, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateFee", reflect.TypeOf((*MockRPCProviderV10Copy)(nil).EstimateFee), ctx, requests, simulationFlags, blockID)
}

// IsSyncing mocks base method.
func (m *MockRPCProviderV10Copy) IsSyncing(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSyncing", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSyncing indicates an expected call of IsSyncing.
func (mr *MockRPCProviderV10CopyMockRecorder) IsSyncing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSyncing", reflect.TypeOf((*MockRPCProviderV10Copy)(nil).IsSyncing), ctx)
}

// Nonce mocks base method.
func (m *MockRPCProviderV10Copy) Nonce(ctx context.Context, blockID types.BlockID, contractAddress *felt.Felt) (*felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nonce", ctx, blockID, contractAddress)
	ret0, _ := ret[0].(*felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Nonce indicates an expected call of Nonce.
func (mr *MockRPCProviderV10CopyMockRecorder) Nonce(ctx, blockID, contractAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nonce", reflect.TypeOf((*MockRPCProviderV10Copy)(nil).Nonce), ctx, blockID, contractAddress)
}

// TransactionByHash mocks base method.
func (m *MockRPCProviderV10Copy) TransactionByHash(ctx context.Context, hash *felt.Felt) (types.BlockTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionByHash", ctx, hash)
	ret0, _ := ret[0].(types.BlockTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionByHash indicates an expected call of TransactionByHash.
func (mr *MockRPCProviderV10CopyMockRecorder) TransactionByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionByHash", reflect.TypeOf((*MockRPCProviderV10Copy)(nil).TransactionByHash), ctx, hash)
}

// TransactionReceipt mocks base method.
func (m *MockRPCProviderV10Copy) TransactionReceipt(ctx context.Context, transactionHash *felt.Felt) (types.TransactionReceiptWithBlockInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionReceipt", ctx, transactionHash)
	ret0, _ := ret[0].(types.TransactionReceiptWithBlockInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionReceipt indicates an expected call of TransactionReceipt.
func (mr *MockRPCProviderV10CopyMockRecorder) TransactionReceipt(ctx, transactionHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionReceipt", reflect.TypeOf((*MockRPCProviderV10Copy)(nil).TransactionReceipt), ctx, transactionHash)
}

// TransactionStatus mocks base method.
func (m *MockRPCProviderV10Copy) TransactionStatus(ctx context.Context, transactionHash *felt.Felt) (types.TxnStatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionStatus", ctx, transactionHash)
	ret0, _ := ret[0].(types.TxnStatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionStatus indicates an expected call of TransactionStatus.
func (mr *MockRPCProviderV10CopyMockRecorder) TransactionStatus(ctx, transactionHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionStatus", reflect.TypeOf((*MockRPCProviderV10Copy)(nil).TransactionStatus), ctx, transactionHash)
}

// MockOtherMethods is a mock of OtherMethods interface.
type MockOtherMethods struct {
	ctrl     *gomock.Controller
	recorder *MockOtherMethodsMockRecorder
	isgomock struct{}
}

// MockOtherMethodsMockRecorder is the mock recorder for MockOtherMethods.
type MockOtherMethodsMockRecorder struct {
	mock *MockOtherMethods
}

// NewMockOtherMethods creates a new mock instance.
func NewMockOtherMethods(ctrl *gomock.Controller) *MockOtherMethods {
	mock := &MockOtherMethods{ctrl: ctrl}
	mock.recorder = &MockOtherMethodsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOtherMethods) EXPECT() *MockOtherMethodsMockRecorder {
	return m.recorder
}

// AsV10 mocks base method.
func (m *MockOtherMethods) AsV10() rpcv10.RPCProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsV10")
	ret0, _ := ret[0].(rpcv10.RPCProvider)
	return ret0
}

// AsV10 indicates an expected call of AsV10.
func (mr *MockOtherMethodsMockRecorder) AsV10() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsV10", reflect.TypeOf((*MockOtherMethods)(nil).AsV10))
}

// AsV9 mocks base method.
func (m *MockOtherMethods) AsV9() rpcv9.RPCProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsV9")
	ret0, _ := ret[0].(rpcv9.RPCProvider)
	return ret0
}

// AsV9 indicates an expected call of AsV9.
func (mr *MockOtherMethodsMockRecorder) AsV9() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsV9", reflect.TypeOf((*MockOtherMethods)(nil).AsV9))
}

// EstimateTip mocks base method.
func (m *MockOtherMethods) EstimateTip(ctx context.Context, multiplier float64) (types.U64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateTip", ctx, multiplier)
	ret0, _ := ret[0].(types.U64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateTip indicates an expected call of EstimateTip.
func (mr *MockOtherMethodsMockRecorder) EstimateTip(ctx, multiplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateTip", reflect.TypeOf((*MockOtherMethods)(nil).EstimateTip), ctx, multiplier)
}

// SendTransaction mocks base method.
func (m *MockOtherMethods) SendTransaction(ctx context.Context, txn types.BroadcastTxn) (types.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTransaction", ctx, txn)
	ret0, _ := ret[0].(types.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTransaction indicates an expected call of SendTransaction.
func (mr *MockOtherMethodsMockRecorder) SendTransaction(ctx, txn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTransaction", reflect.TypeOf((*MockOtherMethods)(nil).SendTransaction), ctx, txn)
}

// BasicRPC is a mock of BasicProviderInterface interface.
type BasicRPC struct {
	ctrl     *gomock.Controller
	recorder *BasicRPCMockRecorder
	isgomock struct{}
}

// BasicRPCMockRecorder is the mock recorder for BasicRPC.
type BasicRPCMockRecorder struct {
	mock *BasicRPC
}

// NewBasicRPC creates a new mock instance.
func NewBasicRPC(ctrl *gomock.Controller) *BasicRPC {
	mock := &BasicRPC{ctrl: ctrl}
	mock.recorder = &BasicRPCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *BasicRPC) EXPECT() *BasicRPCMockRecorder {
	return m.recorder
}

// AsV10 mocks base method.
func (m *BasicRPC) AsV10() rpcv10.RPCProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsV10")
	ret0, _ := ret[0].(rpcv10.RPCProvider)
	return ret0
}

// AsV10 indicates an expected call of AsV10.
func (mr *BasicRPCMockRecorder) AsV10() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsV10", reflect.TypeOf((*BasicRPC)(nil).AsV10))
}

// AsV9 mocks base method.
func (m *BasicRPC) AsV9() rpcv9.RPCProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsV9")
	ret0, _ := ret[0].(rpcv9.RPCProvider)
	return ret0
}

// AsV9 indicates an expected call of AsV9.
func (mr *BasicRPCMockRecorder) AsV9() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsV9", reflect.TypeOf((*BasicRPC)(nil).AsV9))
}

// BlockHashAndNumber mocks base method.
func (m *BasicRPC) BlockHashAndNumber(ctx context.Context) (uint64, *felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockHashAndNumber", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(*felt.Felt)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BlockHashAndNumber indicates an expected call of BlockHashAndNumber.
func (mr *BasicRPCMockRecorder) BlockHashAndNumber(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockHashAndNumber", reflect.TypeOf((*BasicRPC)(nil).BlockHashAndNumber), ctx)
}

// Call mocks base method.
func (m *BasicRPC) Call(ctx context.Context, call types.FunctionCall, block types.BlockID) ([]*felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", ctx, call, block)
	ret0, _ := ret[0].([]*felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Call indicates an expected call of Call.
func (mr *BasicRPCMockRecorder) Call(ctx, call, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*BasicRPC)(nil).Call), ctx, call, block)
}

// ChainID mocks base method.
func (m *BasicRPC) ChainID(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainID", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChainID indicates an expected call of ChainID.
func (mr *BasicRPCMockRecorder) ChainID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainID", reflect.TypeOf((*BasicRPC)(nil).ChainID), ctx)
}

// EstimateFee mocks base method.
func (m *BasicRPC) EstimateFee(ctx context.Context, requests []types.BroadcastTxn, simulationFlags []types.SimulationFlag, blockID types.BlockID) ([]types.FeeEstimation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateFee", ctx, requests, simulationFlags, blockID)
	ret0, _ := ret[0].([]types.FeeEstimation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateFee indicates an expected call of EstimateFee.
func (mr *BasicRPCMockRecorder) EstimateFee(ctx, requests, simulationFlags, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateFee", reflect.TypeOf((*BasicRPC)(nil).EstimateFee), ctx, requests, simulationFlags, blockID)
}

// EstimateTip mocks base method.
func (m *BasicRPC) EstimateTip(ctx context.Context, multiplier float64) (types.U64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateTip", ctx, multiplier)
	ret0, _ := ret[0].(types.U64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateTip indicates an expected call of EstimateTip.
func (mr *BasicRPCMockRecorder) EstimateTip(ctx, multiplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateTip", reflect.TypeOf((*BasicRPC)(nil).EstimateTip), ctx, multiplier)
}

// IsSyncing mocks base method.
func (m *BasicRPC) IsSyncing(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSyncing", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSyncing indicates an expected call of IsSyncing.
func (mr *BasicRPCMockRecorder) IsSyncing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSyncing", reflect.TypeOf((*BasicRPC)(nil).IsSyncing), ctx)
}

// Nonce mocks base method.
func (m *BasicRPC) Nonce(ctx context.Context, blockID types.BlockID, contractAddress *felt.Felt) (*felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nonce", ctx, blockID, contractAddress)
	ret0, _ := ret[0].(*felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Nonce indicates an expected call of Nonce.
func (mr *BasicRPCMockRecorder) Nonce(ctx, blockID, contractAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nonce", reflect.TypeOf((*BasicRPC)(nil).Nonce), ctx, blockID, contractAddress)
}

// SendTransaction mocks base method.
func (m *BasicRPC) SendTransaction(ctx context.Context, txn types.BroadcastTxn) (types.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTransaction", ctx, txn)
	ret0, _ := ret[0].(types.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTransaction indicates an expected call of SendTransaction.
func (mr *BasicRPCMockRecorder) SendTransaction(ctx, txn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTransaction", reflect.TypeOf((*BasicRPC)(nil).SendTransaction), ctx, txn)
}

// TransactionByHash mocks base method.
func (m *BasicRPC) TransactionByHash(ctx context.Context, hash *felt.Felt) (types.BlockTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionByHash", ctx, hash)
	ret0, _ := ret[0].(types.BlockTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionByHash indicates an expected call of TransactionByHash.
func (mr *BasicRPCMockRecorder) TransactionByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionByHash", reflect.TypeOf((*BasicRPC)(nil).TransactionByHash), ctx, hash)
}

// TransactionReceipt mocks base method.
func (m *BasicRPC) TransactionReceipt(ctx context.Context, transactionHash *felt.Felt) (types.TransactionReceiptWithBlockInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionReceipt", ctx, transactionHash)
	ret0, _ := ret[0].(types.TransactionReceiptWithBlockInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionReceipt indicates an expected call of TransactionReceipt.
func (mr *BasicRPCMockRecorder) TransactionReceipt(ctx, transactionHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionReceipt", reflect.TypeOf((*BasicRPC)(nil).TransactionReceipt), ctx, transactionHash)
}

// TransactionStatus mocks base method.
func (m *BasicRPC) TransactionStatus(ctx context.Context, transactionHash *felt.Felt) (types.TxnStatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionStatus", ctx, transactionHash)
	ret0, _ := ret[0].(types.TxnStatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionStatus indicates an expected call of TransactionStatus.
func (mr *BasicRPCMockRecorder) TransactionStatus(ctx, transactionHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionStatus", reflect.TypeOf((*BasicRPC)(nil).TransactionStatus), ctx, transactionHash)
}
