// Code generated by MockGen. DO NOT EDIT.
// Source: wrapper.go
//
// Generated by this command:
//
//	mockgen -destination=./wrapper_mock_test.go -package=account -source=wrapper.go providerWrapperI
//

// Package account is a generated GoMock package.
package account

import (
	context "context"
	reflect "reflect"

	felt "github.com/NethermindEth/juno/core/felt"
	rpcv10 "github.com/NethermindEth/starknet.go/rpc/rpcv10"
	rpcv9 "github.com/NethermindEth/starknet.go/rpc/rpcv9"
	types "github.com/NethermindEth/starknet.go/rpc/types"
	gomock "go.uber.org/mock/gomock"
)

// MockproviderWrapper is a mock of providerWrapper interface.
type MockproviderWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockproviderWrapperMockRecorder
	isgomock struct{}
}

// MockproviderWrapperMockRecorder is the mock recorder for MockproviderWrapper.
type MockproviderWrapperMockRecorder struct {
	mock *MockproviderWrapper
}

// NewMockproviderWrapper creates a new mock instance.
func NewMockproviderWrapper(ctrl *gomock.Controller) *MockproviderWrapper {
	mock := &MockproviderWrapper{ctrl: ctrl}
	mock.recorder = &MockproviderWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproviderWrapper) EXPECT() *MockproviderWrapperMockRecorder {
	return m.recorder
}

// AsV10 mocks base method.
func (m *MockproviderWrapper) AsV10() rpcv10.RPCProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsV10")
	ret0, _ := ret[0].(rpcv10.RPCProvider)
	return ret0
}

// AsV10 indicates an expected call of AsV10.
func (mr *MockproviderWrapperMockRecorder) AsV10() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsV10", reflect.TypeOf((*MockproviderWrapper)(nil).AsV10))
}

// AsV9 mocks base method.
func (m *MockproviderWrapper) AsV9() rpcv9.RPCProvider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsV9")
	ret0, _ := ret[0].(rpcv9.RPCProvider)
	return ret0
}

// AsV9 indicates an expected call of AsV9.
func (mr *MockproviderWrapperMockRecorder) AsV9() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsV9", reflect.TypeOf((*MockproviderWrapper)(nil).AsV9))
}

// ChainID mocks base method.
func (m *MockproviderWrapper) ChainID(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainID", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChainID indicates an expected call of ChainID.
func (mr *MockproviderWrapperMockRecorder) ChainID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainID", reflect.TypeOf((*MockproviderWrapper)(nil).ChainID), ctx)
}

// EstimateFee mocks base method.
func (m *MockproviderWrapper) EstimateFee(ctx context.Context, requests []types.BroadcastTxn, simulationFlags []types.SimulationFlag, blockID types.BlockID) ([]types.FeeEstimation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateFee", ctx, requests, simulationFlags, blockID)
	ret0, _ := ret[0].([]types.FeeEstimation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateFee indicates an expected call of EstimateFee.
func (mr *MockproviderWrapperMockRecorder) EstimateFee(ctx, requests, simulationFlags, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateFee", reflect.TypeOf((*MockproviderWrapper)(nil).EstimateFee), ctx, requests, simulationFlags, blockID)
}

// EstimateTip mocks base method.
func (m *MockproviderWrapper) EstimateTip(ctx context.Context, multiplier float64) (types.U64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateTip", ctx, multiplier)
	ret0, _ := ret[0].(types.U64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateTip indicates an expected call of EstimateTip.
func (mr *MockproviderWrapperMockRecorder) EstimateTip(ctx, multiplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateTip", reflect.TypeOf((*MockproviderWrapper)(nil).EstimateTip), ctx, multiplier)
}

// Nonce mocks base method.
func (m *MockproviderWrapper) Nonce(ctx context.Context, blockID types.BlockID, contractAddress *felt.Felt) (*felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nonce", ctx, blockID, contractAddress)
	ret0, _ := ret[0].(*felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Nonce indicates an expected call of Nonce.
func (mr *MockproviderWrapperMockRecorder) Nonce(ctx, blockID, contractAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nonce", reflect.TypeOf((*MockproviderWrapper)(nil).Nonce), ctx, blockID, contractAddress)
}

// SendTransaction mocks base method.
func (m *MockproviderWrapper) SendTransaction(ctx context.Context, txn types.BroadcastTxn) (TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTransaction", ctx, txn)
	ret0, _ := ret[0].(TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTransaction indicates an expected call of SendTransaction.
func (mr *MockproviderWrapperMockRecorder) SendTransaction(ctx, txn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTransaction", reflect.TypeOf((*MockproviderWrapper)(nil).SendTransaction), ctx, txn)
}

// TransactionByHash mocks base method.
func (m *MockproviderWrapper) TransactionByHash(ctx context.Context, hash *felt.Felt) (types.BlockTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionByHash", ctx, hash)
	ret0, _ := ret[0].(types.BlockTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionByHash indicates an expected call of TransactionByHash.
func (mr *MockproviderWrapperMockRecorder) TransactionByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionByHash", reflect.TypeOf((*MockproviderWrapper)(nil).TransactionByHash), ctx, hash)
}

// TransactionReceipt mocks base method.
func (m *MockproviderWrapper) TransactionReceipt(ctx context.Context, transactionHash *felt.Felt) (types.TransactionReceiptWithBlockInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionReceipt", ctx, transactionHash)
	ret0, _ := ret[0].(types.TransactionReceiptWithBlockInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionReceipt indicates an expected call of TransactionReceipt.
func (mr *MockproviderWrapperMockRecorder) TransactionReceipt(ctx, transactionHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionReceipt", reflect.TypeOf((*MockproviderWrapper)(nil).TransactionReceipt), ctx, transactionHash)
}

// TransactionStatus mocks base method.
func (m *MockproviderWrapper) TransactionStatus(ctx context.Context, transactionHash *felt.Felt) (types.TxnStatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionStatus", ctx, transactionHash)
	ret0, _ := ret[0].(types.TxnStatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionStatus indicates an expected call of TransactionStatus.
func (mr *MockproviderWrapperMockRecorder) TransactionStatus(ctx, transactionHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionStatus", reflect.TypeOf((*MockproviderWrapper)(nil).TransactionStatus), ctx, transactionHash)
}

// Version mocks base method.
func (m *MockproviderWrapper) Version() RPCVersion {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(RPCVersion)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockproviderWrapperMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockproviderWrapper)(nil).Version))
}
