// Code generated by MockGen. DO NOT EDIT.
// Source: account.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	felt "github.com/NethermindEth/juno/core/felt"
	rpc "github.com/NethermindEth/starknet.go/rpc"
	gomock "github.com/golang/mock/gomock"
)

// MockAccountInterface is a mock of AccountInterface interface.
type MockAccountInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccountInterfaceMockRecorder
}

// MockAccountInterfaceMockRecorder is the mock recorder for MockAccountInterface.
type MockAccountInterfaceMockRecorder struct {
	mock *MockAccountInterface
}

// NewMockAccountInterface returns a new instance of MockAccountInterface.
//
// Parameters:
// - ctrl: The gomock.Controller used for creating the mock.
// Returns:
// - *MockAccountInterface: a pointer to the newly created MockAccountInterface.
func NewMockAccountInterface(ctrl *gomock.Controller) *MockAccountInterface {
	mock := &MockAccountInterface{ctrl: ctrl}
	mock.recorder = &MockAccountInterfaceMockRecorder{mock}
	return mock
}

// EXPECT is a function that returns a pointer to a MockAccountInterfaceMockRecorder
// (allows the caller to indicate expected use).
//
// Parameters:
//  none
// Returns:
// - *MockAccountInterfaceMockRecorder: a pointer to a MockAccountInterfaceMockRecorder
func (m *MockAccountInterface) EXPECT() *MockAccountInterfaceMockRecorder {
	return m.recorder
}

// Call is a method that performs some operation.
//
// Parameters:
// - ctx: the context
// - call: the rpc.FunctionCall
// Returns:
// - []*felt.Felt: a slice of *felt.Felt
// - error: an error if any
func (m *MockAccountInterface) Call(ctx context.Context, call rpc.FunctionCall) ([]*felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", ctx, call)
	ret0, _ := ret[0].([]*felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Call is a function that records a call to the Call method of the MockAccountInterface interface.
//
// Parameters:
// - ctx: the context
// - call: the interface representing the call
// Returns:
// - *gomock.Call: a pointer to the Call
func (mr *MockAccountInterfaceMockRecorder) Call(ctx, call interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockAccountInterface)(nil).Call), ctx, call)
}

// TransactionHash is a method of the MockAccountInterface struct.
//
// Parameters:
// - calls: rpc.FunctionCall
// - txDetails: rpc.TxDetails
// Returns:
// - *felt.Felt: a pointer 
// - error: an error if any
func (m *MockAccountInterface) TransactionHash(calls rpc.FunctionCall, txDetails rpc.TxDetails) (*felt.Felt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionHash", calls, txDetails)
	ret0, _ := ret[0].(*felt.Felt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionHash description of an expected call of TransactionHash.
//
// Parameter(s):
// - calls: rpc.FunctionCall
// - txDetails: interface{}
// Returns:
// - *gomock.Call: a pointer to the Call.
func (mr *MockAccountInterfaceMockRecorder) TransactionHash(calls, txDetails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionHash", reflect.TypeOf((*MockAccountInterface)(nil).TransactionHash), calls, txDetails)
}
