name: 'Checkout and setup Go'
runs:
  using: "composite"
  steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod