package main

import (
	"fmt"
	"log"

	"github.com/NethermindEth/starknet.go/contracts"
)

func main() {
	// Path to the compiled CASM file (generated by Scarb build process)
	casmPath := "counter_contract/target/dev/counter_Counter.compiled_contract_class.json"

	// Load and unmarshal the CASM class from file
	casmClass, err := contracts.UnmarshalCasmClass(casmPath)
	if err != nil {
		log.Fatalf("Failed to unmarshal CASM class: %v", err)
	}

	// Display CASM class information
	fmt.Printf("Compiler Version: %s\n", casmClass.CompilerVersion)
	fmt.Printf("Bytecode Length: %d instructions\n", len(casmClass.ByteCode))
	fmt.Printf("Entry Points: %d external functions\n", len(casmClass.EntryPointsByType.External))

	// Display entry point details
	for _, ep := range casmClass.EntryPointsByType.External {
		fmt.Printf("  Selector: %s, Offset: %d\n", ep.Selector.String(), ep.Offset)
	}
}
