name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      # General Linter code wide 
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
      # Linter for diffs only. Apply new lint rules gradually that would be a huge refactor
      # to do in one go
      - name: golangci-lint-diffs
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --config=./.golangci_diff.yaml
          only-new-issues: true

