name: (main) Auto CI run

on:
  pull_request:
    branches:
      - "main"

jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    services:
      devnet:
        image: shardlabs/starknet-devnet-rs:0.0.5
        ports:
          - 5050:5050

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: wait for devnet to be up...
        run: ./.bin/devnet.sh

      # Test rpc on devnet
      - name: Test RPC on devnet
        run: cd rpc && go test -timeout 600s -v -env devnet .
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          HTTP_PROVIDER_URL: "http://localhost:5050/"

      # Test rpc on mock
      - name: Test RPC with mocks
        run: cd rpc && go test -v .

      # Test rpc on testnet
      - name: Test RPC on testnet
        run: cd rpc && go test -timeout 1200s -v -env testnet .
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          HTTP_PROVIDER_URL: "https://free-rpc.nethermind.io/sepolia-juno"
          WS_PROVIDER_URL: "wss://ethereum-rpc.publicnode.com" # TODO: change to a Starknet ws node before merge

      # Test rpc on mainnet
      - name: Test RPC with mainnet
        run: echo "Skip for now - need public endpoint that follows rpc spec"
        #run: cd rpc && go test -timeout 600s -v -env mainnet .
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          HTTP_PROVIDER_URL: "https://free-rpc.nethermind.io/mainnet-juno"
          WS_PROVIDER_URL: "wss://ethereum-rpc.publicnode.com" # TODO: change to a Starknet ws node before merge

      # Test Account on devnet
      - name: Test Account on devnet
        run: cd account && go test -timeout 600s -v -env devnet .
        env:
          TESTNET_ACCOUNT_PRIVATE_KEY: ${{ secrets.TESTNET_ACCOUNT_PRIVATE_KEY }}
          HTTP_PROVIDER_URL: "http://localhost:5050"

      # Test Account on mock
      - name: Test Account with mocks
        run: cd account && go test -v . -env mock

      # Build examples
      - name: Build examples
        run: |
          cd examples/deployAccount && go build
          cd ../simpleCall && go build
          cd ../simpleInvoke && go build
          cd ../deployContractUDC && go build
          cd ../typedData && go build
          cd ../websocket && go build

      # Test client on mock
      - name: Test client with mocks
        run: cd client && go test -v


#TODO: handle websocket tests in the CI