name: devnet tests

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-devnet-tests:
    runs-on: ubuntu-22.04

    services:
      devnet:
        image: shardlabs/starknet-devnet-rs:0.5.0
        ports:
          - 5050:5050

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: wait for devnet to be up...
        run: ./.bin/devnet.sh

      - name: Run devnet tests
        run: cd devnet && go test -timeout 300s -v -env devnet .

      - name: Run Account tests on devnet
        run: cd account && go test -timeout 300s -v -env devnet .
        env:
          HTTP_PROVIDER_URL: "http://localhost:5050"

      - name: Run RPC tests on devnet
        run: cd rpc && go test -timeout 300s -v -env devnet .
        env:
          HTTP_PROVIDER_URL: "http://localhost:5050/"
